services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tailadmin_laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tailadmin_network

  web:
    image: satyasy/tailadmin-laravel:beta
    ports:
      - "8090:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tailadmin_laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    networks:
      - tailadmin_network

volumes:
  mysql_data:

networks:
  tailladmin_network:
    driver: bridge
