version: '3.8'

services:
  app:
    image: satyasy-tailadmin-laravel:beta
    build:
      context: .
    container_name: tailadmin-laravel
    ports:
      - "8090:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: >
      sh -c "
        cp .env.example .env &&
        composer install &&
        npm install &&
        npm run hot &&
        php artisan key:generate &&
        php artisan migrate --seed --force &&
        php artisan storage:link &&
        php artisan serve --host=0.0.0.0 --port=9000
      "

  db:
    image: mysql:8
    container_name: tailadmin-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
